function replaceVars( ) {

echo "resources home = $1"
    cd $1
    find ./apim ./apim-analytics ./is-as-km ./nginx ./centos7 -type f | while read FILE
    do
    echo "atualizando arquivo $FILE"
    sed -i "s,{{DB_MAX_ACTIVE}},$DB_MAX_ACTIVE,g" $FILE
    sed -i "s,{{CARBON_HOSTNAME}},$CARBON_HOSTNAME,g" $FILE
    sed -i "s,{{CARBON_MGT_HOSTNAME}},$CARBON_MGT_HOSTNAME,g" $FILE
    sed -i "s,{{WSO2AM_DB_JDBC_URL}},$WSO2AM_DB_JDBC_URL,g" $FILE
    sed -i "s,{{WSO2AM_DB_USERNAME}},$WSO2AM_DB_USERNAME,g" $FILE
    sed -i "s,{{WSO2AM_DB_PASSWORD}},$WSO2AM_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2AM_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2AM_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i "s,{{WSO2AM_STAT_DB_JDBC_URL}},$WSO2AM_STAT_DB_JDBC_URL,g" $FILE
    sed -i "s,{{WSO2AM_STAT_DB_USERNAME}},$WSO2AM_STAT_DB_USERNAME,g" $FILE
    sed -i "s,{{WSO2AM_STAT_DB_PASSWORD}},$WSO2AM_STAT_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2AM_STAT_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2AM_STAT_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{WSO2_MB_STORE_DB_JDBC_URL}},$WSO2_MB_STORE_DB_JDBC_URL,g" $FILE
    sed -i  "s,{{WSO2_MB_STORE_DB_USERNAME}},$WSO2_MB_STORE_DB_USERNAME,g" $FILE
    sed -i  "s,{{WSO2_MB_STORE_DB_PASSWORD}},$WSO2_MB_STORE_DB_PASSWORD,g" $FILE
    sed -i  "s,{{WSO2_MB_STORE_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2_MB_STORE_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{WSO2_METRICS_DB_JDBC_URL}},$WSO2_METRICS_DB_JDBC_URL,g" $FILE
    sed -i  "s,{{WSO2_METRICS_DB_USERNAME}},$WSO2_METRICS_DB_USERNAME,g" $FILE
    sed -i  "s,{{WSO2_METRICS_DB_PASSWORD}},$WSO2_METRICS_DB_PASSWORD,g" $FILE
    sed -i  "s,{{WSO2_METRICS_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2_METRICS_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{CARBON_DB_JDBC_URL}},$CARBON_DB_JDBC_URL,g" $FILE
    sed -i  "s,{{CARBON_DB_USERNAME}},$CARBON_DB_USERNAME,g" $FILE
    sed -i  "s,{{CARBON_DB_PASSWORD}},$CARBON_DB_PASSWORD,g" $FILE
    sed -i "s,{{CARBON_DB_JDBC_DRIVER_CLASS_NAME}},$CARBON_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{WSO2UM_DB_JDBC_URL}},$WSO2UM_DB_JDBC_URL,g" $FILE
    sed -i  "s,{{WSO2UM_DB_USERNAME}},$WSO2UM_DB_USERNAME,g" $FILE
    sed -i  "s,{{WSO2UM_DB_PASSWORD}},$WSO2UM_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2UM_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2UM_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{WSO2GOV_DB_JDBC_URL}},$WSO2GOV_DB_JDBC_URL,g" $FILE
    sed -i  "s,{{WSO2GOV_DB_USERNAME}},$WSO2GOV_DB_USERNAME,g" $FILE
    sed -i  "s,{{WSO2GOV_DB_PASSWORD}},$WSO2GOV_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2GOV_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2GOV_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i  "s,{{IS_AS_KM_HOSTNAME}},$IS_AS_KM_HOSTNAME,g" $FILE
    sed -i  "s,{{IS_AS_KM_PORT}},$IS_AS_KM_PORT,g" $FILE
    sed -i  "s,{{WSO2IS_ANALYTICS_HOSTNAME}},$WSO2IS_ANALYTICS_HOSTNAME,g" $FILE
    sed -i  "s,{{WSO2IS_ANALYTICS_PORT}},$WSO2IS_ANALYTICS_PORT,g" $FILE
    sed -i  "s,{{WSO2AM_ANALYTICS_HOSTNAME}},$WSO2AM_ANALYTICS_HOSTNAME,g" $FILE
    sed -i  "s,{{WSO2AM_ANALYTICS_PORT}},$WSO2AM_ANALYTICS_PORT,g" $FILE
    sed -i  "s,{{WSO2AM_HOSTNAME}},$WSO2AM_HOSTNAME,g" $FILE
    sed -i  "s,{{APIGATEWAY_URL}},$APIGATEWAY_URL,g" $FILE
    sed -i  "s,{{APIGATEWAY_SERVICES_URL}},$APIGATEWAY_SERVICES_URL,g" $FILE
    sed -i  "s,{{APISTORE_URL}},$APISTORE_URL,g" $FILE
    sed -i  "s,{{APIPUBLISHER_URL}},$APIPUBLISHER_URL,g" $FILE
    sed -i  "s,{{APISTORE_HOSTNAME}},$APISTORE_HOSTNAME,g" $FILE
    sed -i "s,{{REVERSE_PROXY_ENABLED}},$REVERSE_PROXY_ENABLED,g" $FILE
    sed -i "s,{{APISTORE_CONTEXT}},$APISTORE_CONTEXT,g" $FILE
    sed -i "s,{{CARBON_OFFSET}},$CARBON_OFFSET,g" $FILE
    sed -i "s,{{APIPUBLISHER_CONTEXT}},$APIPUBLISHER_CONTEXT,g" $FILE
    sed -i "s,{{APIADMIN_CONTEXT}},$APIADMIN_CONTEXT,g" $FILE
    sed -i "s,{{APIADMIN_URL}},$APIADMIN_URL,g" $FILE
    sed -i "s,{{RECEIVER_URL_GROUP}},$RECEIVER_URL_GROUP,g" $FILE
    sed -i "s,{{AUTH_URL_GROUP}},$AUTH_URL_GROUP,g" $FILE
    sed -i "s,{{TRAFFIC_MANAGER}},$TRAFFIC_MANAGER,g" $FILE
    sed -i "s,{{APIM_ANALYTICS_CARBON_OFFSET}},$APIM_ANALYTICS_CARBON_OFFSET,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_DATA_DB_JDBC_URL}},$WSO2AM_ANALYTICS_DATA_DB_JDBC_URL,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_DATA_DB_USERNAME}},$WSO2AM_ANALYTICS_DATA_DB_USERNAME,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_DATA_DB_PASSWORD}},$WSO2AM_ANALYTICS_DATA_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_DATA_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2AM_ANALYTICS_DATA_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_EVENT_DB_JDBC_URL}},$WSO2AM_ANALYTICS_EVENT_DB_JDBC_URL,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_EVENT_DB_USERNAME}},$WSO2AM_ANALYTICS_EVENT_DB_USERNAME,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_EVENT_DB_PASSWORD}},$WSO2AM_ANALYTICS_EVENT_DB_PASSWORD,g" $FILE
    sed -i "s,{{WSO2AM_ANALYTICS_EVENT_DB_JDBC_DRIVER_CLASS_NAME}},$WSO2AM_ANALYTICS_EVENT_DB_JDBC_DRIVER_CLASS_NAME,g" $FILE
    done
}