DB="mysql"
DB_MAX_ACTIVE=20
DB_MIN_ACTIVE=5
DB_MAX_IDLE=5
JDBC_HOST_PORT="10.158.0.5:3306"
JDBC_DRIVER_CLASS_NAME="com.mysql.jdbc.Driver"
JDBC_DRIVER_PATH="$RESOURCES_HOME/mysql/mysql-connector-java-5.1.46.jar"
CARBON_HOST="apim.minegames.com.br"
CARBON_MGT_HOSTNAME="apim.minegames.com.br"

CARBON_OFFSET="0"

CARBON_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
CARBON_DB_USERNAME="wso2"
CARBON_DB_PASSWORD="wso2123"
CARBON_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

WSO2UM_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
WSO2UM_DB_USERNAME="wso2"
WSO2UM_DB_PASSWORD="wso2123"
WSO2UM_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

WSO2GOV_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
WSO2GOV_DB_USERNAME="wso2"
WSO2GOV_DB_PASSWORD="wso2123"
WSO2GOV_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

WSO2AM_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
WSO2AM_DB_USERNAME="wso2"
WSO2AM_DB_PASSWORD="wso2123"
WSO2AM_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

WSO2AM_STAT_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2stat?useSSL=false"
WSO2AM_STAT_DB_USERNAME="wso2stat"
WSO2AM_STAT_DB_PASSWORD="wso2123"
WSO2AM_STAT_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

# MB_STORE ORACLE
WSO2_MB_STORE_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
WSO2_MB_STORE_DB_USERNAME="wso2"
WSO2_MB_STORE_DB_PASSWORD="wso2123"
WSO2_MB_STORE_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

#MB_STORE H2 
#WSO2_MB_STORE_DB_JDBC_URL="jdbc:h2:repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"
#WSO2_MB_STORE_DB_USERNAME="wso2carbon"
#WSO2_MB_STORE_DB_PASSWORD="wso2carbon"
#WSO2_MB_STORE_DB_JDBC_DRIVER_CLASS_NAME="org.h2.Driver"

# METRICS ORACLE
WSO2_METRICS_DB_JDBC_URL="jdbc:mysql://$JDBC_HOST_PORT/wso2?useSSL=false"
WSO2_METRICS_DB_USERNAME="wso2"
WSO2_METRICS_DB_PASSWORD="wso2123"
WSO2_METRICS_DB_JDBC_DRIVER_CLASS_NAME=$JDBC_DRIVER_CLASS_NAME

# METRICS H2
#WSO2_METRICS_DB_JDBC_URL="jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
#WSO2_METRICS_DB_USERNAME="wso2carbon"
#WSO2_METRICS_DB_PASSWORD="wso2carbon"
#WSO2_METRICS_DB_JDBC_DRIVER_CLASS_NAME="org.h2.Driver"

WSO2AM_HOSTNAME="apim.minegames.com.br"
APIM_SSL_CERTIFICATE="apim.minegames.com.br.cer"
APIM_SSL_KEY="apim.minegames.com.br.key"
GATEWAY_SSL_CERTIFICATE="gateway.minegames.com.br.cer"
GATEWAY_SSL_KEY="gateway.minegames.com.br.key"
APIM_IP_ADDRESS="10.158.0.2"
GATEWAY_IP_ADDRESS="10.158.0.2"

APISTORE_URL="apim.minegames.com.br"
APIPUBLISHER_URL="apim.minegames.com.br"
REVERSE_PROXY_ENABLED="true"
APISTORE_CONTEXT="/store"
APIADMIN_URL="apim.minegames.com.br"
APIADMIN_CONTEXT="/admin"
APIPUBLISHER_CONTEXT="/publisher"

APISTORE_HOSTNAME="apim.minegames.com.br"
APIGATEWAY_URL="https://gateway.minegames.com.br"

WSO2AM_ANALYTICS_HOSTNAME="analytics-apim.minegames.com.br"
WSO2AM_ANALYTICS_PORT="443"

WSO2IS_ANALYTICS_HOSTNAME="analytics-is.minegames.com.br"
WSO2IS_ANALYTICS_PORT="443"

IS_AS_KM_HOSTNAME="identity.minegames.com.br"
IS_AS_KM_PORT="443"

