#!/bin/bash 

_VARS=("DB_MAX_ACTIVE" "CARBON_HOSTNAME" "CARBON_HOST" "CARBON_DNS" "CARBON_MGT_HOSTNAME" "WSO2AM_DB_JDBC_URL" "WSO2AM_DB_USERNAME" "WSO2AM_DB_PASSWORD" "WSO2AM_DB_JDBC_DRIVER_CLASS_NAME" "WSO2AM_STAT_DB_JDBC_URL" "WSO2AM_STAT_DB_USERNAME" "WSO2AM_STAT_DB_PASSWORD" "WSO2AM_STAT_DB_JDBC_DRIVER_CLASS_NAME" "WSO2_MB_STORE_DB_JDBC_URL" "WSO2_MB_STORE_DB_USERNAME" "WSO2_MB_STORE_DB_PASSWORD" "WSO2_MB_STORE_DB_JDBC_DRIVER_CLASS_NAME" "WSO2_METRICS_DB_JDBC_URL" "WSO2_METRICS_DB_USERNAME" "WSO2_METRICS_DB_PASSWORD" "WSO2_METRICS_DB_JDBC_DRIVER_CLASS_NAME" "CARBON_DB_JDBC_URL" "CARBON_DB_USERNAME" "CARBON_DB_PASSWORD" "CARBON_DB_JDBC_DRIVER_CLASS_NAME" "WSO2UM_DB_JDBC_URL" "WSO2UM_DB_USERNAME" "WSO2UM_DB_PASSWORD" "WSO2UM_DB_JDBC_DRIVER_CLASS_NAME" "WSO2GOV_DB_JDBC_URL" "WSO2GOV_DB_USERNAME" "WSO2GOV_DB_PASSWORD" "WSO2GOV_DB_JDBC_DRIVER_CLASS_NAME" "IS_AS_KM_HOSTNAME" "IS_AS_KM_PORT" "IS_ANALYTICS_ENABLED" "IS_ANALYTICS_API_URL" "IS_ANALYTICS_SERVER_URL" "WSO2IS_ANALYTICS_HOSTNAME" "WSO2IS_ANALYTICS_PORT" "WSO2AM_ANALYTICS_HOSTNAME" "WSO2AM_ANALYTICS_PORT" "WSO2AM_HOSTNAME" "APIGATEWAY_URL" "APIGATEWAY_DNS" "APIGATEWAY_SERVICES_URL" "APISTORE_URL" "APISTORE_DNS" "APIPUBLISHER_URL" "APIPUBLISHER_DNS" "APISTORE_HOSTNAME" "REVERSE_PROXY_ENABLED" "APISTORE_CONTEXT" "CARBON_OFFSET" "APIPUBLISHER_CONTEXT" "APIADMIN_CONTEXT" "APIADMIN_URL" "RECEIVER_URL_GROUP" "AUTH_URL_GROUP" "TRAFFIC_MANAGER" "TM_DNS" "BROKER_LIST" "AM_ANALYTICS_ENABLED" "AM_ANALYTICS_API_URL" "AM_ANALYTICS_SERVER_URL" "APIM_ANALYTICS_CARBON_OFFSET" "WSO2AM_ANALYTICS_DATA_DB_JDBC_URL" "WSO2AM_ANALYTICS_DATA_DB_USERNAME" "WSO2AM_ANALYTICS_DATA_DB_PASSWORD" "WSO2AM_ANALYTICS_DATA_DB_JDBC_DRIVER_CLASS_NAME" "WSO2AM_ANALYTICS_EVENT_DB_JDBC_URL" "WSO2AM_ANALYTICS_EVENT_DB_USERNAME" "WSO2AM_ANALYTICS_EVENT_DB_PASSWORD" "WSO2AM_ANALYTICS_EVENT_DB_JDBC_DRIVER_CLASS_NAME" "SSL_HOSTNAME_VERIFIER" "REGISTRY_IDEXING_FREQUENCY_IN_SECONDS" "REGISTRY_INDEXING_BATCH_SIZE" "REGISTRY_INDEXER_POOL_SIZE" "WSO2IS_STAT_DB_JDBC_URL" "WSO2IS_STAT_DB_USERNAME" "WSO2IS_STAT_DB_PASSWORD" "WSO2IS_STAT_DB_JDBC_DRIVER_CLASS_NAME" "WSO2IS_ANALYTICS_DATA_DB_JDBC_URL" "WSO2IS_ANALYTICS_DATA_DB_USERNAME" "WSO2IS_ANALYTICS_DATA_DB_PASSWORD" "WSO2IS_ANALYTICS_DATA_DB_JDBC_DRIVER_CLASS_NAME" "WSO2IS_ANALYTICS_EVENT_DB_JDBC_URL" "WSO2IS_ANALYTICS_EVENT_DB_USERNAME" "WSO2IS_ANALYTICS_EVENT_DB_PASSWORD" "WSO2IS_ANALYTICS_EVENT_DB_JDBC_DRIVER_CLASS_NAME" "CARBON_LOGFILE_MAXFILESIZE" "CARBON_LOGFILE_MAXBACKUPINDEX")

function setCarbonHomeByProduct( ) {

    echo "entrou no getCarbonHomeByProduct $1"
    if [ "$1" = "is-analytics" ]; then
        CARBON_HOME="/opt/wso2/wso2is-analytics";
    fi
    if [ "$1" = "apim-analytics" ]; then
        CARBON_HOME="/opt/wso2/wso2am-analytics";
    fi
    if [ "$1" = "apim" ]; then
        CARBON_HOME="/opt/wso2/wso2apim";
    fi
    if [ "$1" = "is-as-km" ]; then
        CARBON_HOME="/opt/wso2/wso2is";
    fi
    if [ "$1" = "is" ]; then
        CARBON_HOME="/opt/wso2/wso2is";
    fi
}

function pre_install() {
    source $1
    source $2

    echo "INFO: (re)criando diretorio com os artefatos /tmp/resources"
    rm -rf $RESOURCES_HOME
    mkdir -p $RESOURCES_HOME
    cp -a $WSO2_INSTALL_PATH/resources/* $RESOURCES_HOME/

    echo "INFO: substituindo variaveis nos arquivos configuracao template"
    source $WSO2_INSTALL_PATH/scripts/functions.sh
    replaceVars $RESOURCES_HOME $1
}

function replaceVars( ) {
    echo "DEBUG: carregar variaveis novamente: $2"
    source $2

    cd $1
    #find ./apim ./apim-analytics ./is-as-km ./nginx ./centos7 ./is-analytics -type f | while read FILE
    echo "DEBUG: atualizando arquivos template"
    echo "DEBUG: imprimindo variavel para verificar se foram carregadas: $WSO2AM_DB_JDBC_URL"
    find ./apim ./apim-analytics ./is-as-km ./nginx ./centos7 ./is-analytics -type f | while read FILE
    do
    #echo "atualizando arquivo $FILE"
        for i in "${_VARS[@]}"
        do
	        echo "substituir $i em $FILE" >> debug.log
            _VALUE="echo $`$i`"
            echo $_VALUE >> debug.log
            sed -i "s,{{$i}},$_VALUE,g" $FILE
        done
    done
}

